
services:
  siap-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Ocr__Provider=Tesseract
      - Ocr__ExecutablePath=/usr/bin/tesseract
      - Ocr__DataPath=/usr/share/tesseract-ocr/5/tessdata
      - Ocr__Language=ind+eng
    volumes:
      - ./Uploads:/app/Uploads
    networks:
      - siap-net

networks:
  siap-net:
    driver: bridge
